import type { Metadata } from "next";
import { Geist, Geist_Mono, Metal } from "next/font/google";
import "./styles/globals.css";
import styles from './styles/layuout.module.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const inter = Metal({
  subsets: ['latin'],
  weight: ['400']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className={styles.main}>
          {children}
        </main>
      </body>
    </html>
  );
}
