import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hone page",
  description: "Generated by create next app",
};

export default async function Home() {
  return (
    <div>
    </div>
  );
}
